training_dataset: /home/dhruv/Downloads/genres
test_size: 0.33
tags:
  - blues
  - classical
  - country
  - disco
  - hiphop
  - jazz
  - metal
  - pop
  - reggae
  - rock

plugins:
  AF: MusicReco.plugins.af_features
  FEXTRACT: MusicReco.plugins.mfcc_mean
  GMM:  MusicReco.plugins.GMM_plugin
  MFCC: MusicReco.plugins.mfcc_simple
  MDELTA: MusicReco.plugins.mfcc_delta
  RHYTHM: MusicReco.plugins.rhythmic
  CHROMA: MusicReco.plugins.chroma_features

db:
  database: databases/simreco.db
